### ISSUE TITLE
Feature request: Seuil de tolérance recherche d'adresse

### ISSUE THREAD

**Issue by MMR100** [sigmoe/ExpressionFunctions#1]
Bonjour, je ne sais pas si vous acceptez les demandes d'amélioration, en tout cas voici une proposition pour le plugin "Fonctions SIGMOÉ'. 
Serait-il possible de pouvoir définir un seuil de distance au delà duquel une adresse est considérée comme fausse?
Par exemple, en pleine campagne, il arrive que des points aient pour résultat une adresse beaucoup trop éloignée. 
En proposant un formule du type get_address('full', 100), les points situés à plus de 100 mètre d'une adresse renverraient NULL comme résultat.

**Comment by sigmoe** [comment]
L'option vient d'être ajoutée dans la nouvelle mise à jour 3.0.2.
